export const FIAT_CURRENCY_NAMES: Record<string, string> = {
  'usd': 'US Dollar',
  'eur': 'Euro',
  'ars': 'Argentine Peso',
  'pen': 'Peruvian Sol',
  'gbp': 'British Pound',
  'jpy': 'Japanese Yen',
  'cad': 'Canadian Dollar',
  'aud': 'Australian Dollar',
  'chf': 'Swiss Franc',
  'cny': 'Chinese Yuan',
  'sek': 'Swedish Krona',
  'nzd': 'New Zealand Dollar',
  'mxn': 'Mexican Peso',
  'sgd': 'Singapore Dollar',
  'hkd': 'Hong Kong Dollar',
  'nok': 'Norwegian Krone',
  'inr': 'Indian Rupee',
  'rub': 'Russian Ruble',
  'zar': 'South African Rand',
  'try': 'Turkish Lira',
  'brl': 'Brazilian Real',
  'krw': 'South Korean Won',
  'thb': 'Thai Baht',
  'myr': 'Malaysian Ringgit',
  'idr': 'Indonesian Rupiah',
  'php': 'Philippine Peso',
  'vnd': 'Vietnamese Dong',
  'bdt': 'Bangladeshi Taka',
  'pkr': 'Pakistani Rupee',
  'lkr': 'Sri Lankan Rupee',
  'mmk': 'Myanmar Kyat',
  'khr': 'Cambodian Riel',
  'lao': 'Lao Kip',
  'kzt': 'Kazakhstani Tenge',
  'uzs': 'Uzbekistani Som',
  'tjs': 'Tajikistani Somoni',
  'tmt': 'Turkmenistan Manat',
  'afn': 'Afghan Afghani',
  'iqd': 'Iraqi Dinar',
  'irr': 'Iranian Rial',
  'omr': 'Omani Rial',
  'qar': 'Qatari Riyal',
  'aed': 'UAE Dirham',
  'bhd': 'Bahraini Dinar',
  'kwd': 'Kuwaiti Dinar',
  'jod': 'Jordanian Dinar',
  'lbp': 'Lebanese Pound',
  'syp': 'Syrian Pound',
  'egp': 'Egyptian Pound',
  'sdg': 'Sudanese Pound',
  'lyd': 'Libyan Dinar',
  'dzd': 'Algerian Dinar',
  'mad': 'Moroccan Dirham',
  'tnd': 'Tunisian Dinar',
  'xof': 'West African CFA Franc',
  'xaf': 'Central African CFA Franc',
  'xpf': 'CFP Franc',
  'cdf': 'Congolese Franc',
  'bif': 'Burundian Franc',
  'rwf': 'Rwandan Franc',
  'ugx': 'Ugandan Shilling',
  'tzs': 'Tanzanian Shilling',
  'kes': 'Kenyan Shilling',
  'etb': 'Ethiopian Birr',
  'sos': 'Somali Shilling',
  'djf': 'Djiboutian Franc',
  'kmf': 'Comorian Franc',
  'mru': 'Mauritanian Ouguiya',
  'sc': 'Seychellois Rupee',
  'szl': 'Eswatini Lilangeni',
  'lsl': 'Lesotho Loti',
  'nad': 'Namibian Dollar',
  'bwp': 'Botswana Pula',
  'zmw': 'Zambian Kwacha',
  'mwk': 'Malawian Kwacha',
  'mzn': 'Mozambican Metical',
  'aoa': 'Angolan Kwanza',
  'stn': 'São Tomé and Príncipe Dobra',
  'cve': 'Cape Verdean Escudo',
  'gmd': 'Gambian Dalasi',
  'gnf': 'Guinean Franc',
  'gwp': 'Guinea-Bissau Peso',
  'mop': 'Macanese Pataca',
  'bob': 'Bolivian Boliviano',
  'pyg': 'Paraguayan Guaraní',
  'vef': 'Venezuelan Bolívar',
  'ves': 'Venezuelan Bolívar Soberano',
  'clp': 'Chilean Peso',
  'cop': 'Colombian Peso',
  'uyu': 'Uruguayan Peso'
};

export const getFiatDisplayName = (fiatId: string): string => {
  return FIAT_CURRENCY_NAMES[fiatId.toLowerCase()] || fiatId.toUpperCase();
};

export const getSupportedFiatCurrencies = (): string[] => {
  return Object.keys(FIAT_CURRENCY_NAMES);
};
